name: 'Paperspace Deploy'
description: 'Upserts a Paperspace Deployment with the specified configuration'
inputs:
  apiKey:
    description: 'Paperspace API Key. Defaults to env.PAPERSPACE_API_KEY.'
    required: false
  projectId:
    description: 'Project ID that the deployment lives under.'
    required: true
  configPath:
    description: 'Relative path to configuration file to deploy.'
    required: false
  image:
    description: 'Optional container image to use for the deployment.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'