name: 'Paperspace Deploy'
description: 'Creates a new paperspace deployment'
inputs:
  apiKey:
    description: 'Paperspace API Key'
    required: false
  projectId:
    description: 'Project ID that the deployment lives under.'
    required: true
  filePath:
    description: 'Relative path to configuration file to deploy.'
    required: false
  image:
    description: 'Optional container image to use for the deployment.'
    required: false
runs:
  using: 'node16'
  main: 'dist/index.js'