name: 'Paperspace Deploy'
description: 'Creates a new paperspace deployment'
inputs:
  paperspaceApiKey:
    description: 'Paperspace API Key'
    required: false
  deploymentId:
    description: 'Container deployment ID'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'dist/index.js'